# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Projects by MarcomorettiM
email: marcomorettim@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  "The website is a blog of Marco Moretti, collectig experiments projects and thoughts."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marcomorettim.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: "marcomorettim/marcomorettim"

social:
  type:  Person # Person or Organization (defaults to Person)
  name:  "Marco Moretti" # If the user or organization name differs from the site's name
  links:
    - "https://twitter.com/marcomorettim"
    - "https://www.linkedin.com/in/marcomorettim"
    - "https://www.github.com/in/marcomorettim"
  author:
  name   : "Marco Moretti"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "The website is a blog of Marco Moretti, collectig experiments projects and thoughts."
  email  : marcomorettim@gmail.com
  uri    : "https://marcomorettim.github.io"

    

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
minimal_mistakes_skin : "air"
locale: en-GB
plugins:
  - jekyll-feed
head_scripts:
  - https://code.jquery.com/jquery-3.2.1.min.js
  - /assets/js/your-custom-head-script.js
teaser: /assets/images/500x300.png
header:
  teaser: /assets/images/my-awesome-post-teaser.jpg
breadcrumbs: true  # disabled by default
permalink: /:categories/:title/
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
paginate: 5
# staticman.yml (defaults)
comments:
  allowedFields      : ["name", "email", "url", "message"]
  branch             : "master"
  commitMessage      : "New comment"
  filename           : "comment-{@timestamp}"
  format             : "yaml"
  generatedFields:
    date:
      type           : "date"
      options:
        format       : "iso8601"
  moderation         : true
  path               : "/_data/comments/{options.slug}" (default)
  requiredFields     : ["name", "email", "message"]
  transforms:
    email            : md5
# _config.yml (defaults)
repository  : "marcomorettim/marcomorettim"# GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
comments:
  provider  : "staticman_v2"
staticman:
  branch    : "master"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
