
title: Projects by MarcomorettiM
email: marcomorettim@gmail.com
description: "The website is a blog of Marco Moretti, collectig experiments projects and thoughts."
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate
  
gems:
  - jemoji
